"""Add news and sentiment tables

Revision ID: 71e9e7c0aa87
Revises: notifications_001
Create Date: 2025-11-24 06:17:43.551659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e9e7c0aa87'
down_revision = 'notifications_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_ticker'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_settings_id'), table_name='notification_settings')
    op.drop_index(op.f('ix_notification_settings_user_id'), table_name='notification_settings')
    op.drop_table('notification_settings')
    op.drop_constraint(op.f('uix_ticker_pred_target_date'), 'daily_predictions', type_='unique')
    op.create_index(op.f('ix_daily_predictions_id'), 'daily_predictions', ['id'], unique=False)
    op.create_index(op.f('ix_daily_predictions_prediction_date'), 'daily_predictions', ['prediction_date'], unique=False)
    op.create_index(op.f('ix_daily_predictions_target_date'), 'daily_predictions', ['target_date'], unique=False)
    op.create_index(op.f('ix_daily_predictions_ticker'), 'daily_predictions', ['ticker'], unique=False)
    op.create_index(op.f('ix_education_articles_id'), 'education_articles', ['id'], unique=False)
    op.add_column('user_progress', sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.drop_column('user_progress', 'completed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_progress', sa.Column('completed_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.create_foreign_key(None, 'user_progress', 'education_articles', ['article_id'], ['id'])
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.drop_column('user_progress', 'viewed_at')
    op.drop_index(op.f('ix_education_articles_id'), table_name='education_articles')
    op.drop_index(op.f('ix_daily_predictions_ticker'), table_name='daily_predictions')
    op.drop_index(op.f('ix_daily_predictions_target_date'), table_name='daily_predictions')
    op.drop_index(op.f('ix_daily_predictions_prediction_date'), table_name='daily_predictions')
    op.drop_index(op.f('ix_daily_predictions_id'), table_name='daily_predictions')
    op.create_unique_constraint(op.f('uix_ticker_pred_target_date'), 'daily_predictions', ['ticker', 'prediction_date', 'target_date'])
    op.create_table('notification_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('price_alert_enabled', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('prediction_update_enabled', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('rebalance_alert_enabled', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('news_alert_enabled', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('portfolio_goal_enabled', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('price_change_threshold', sa.FLOAT(), server_default=sa.text("'5.0'"), nullable=False),
    sa.Column('rebalance_threshold', sa.FLOAT(), server_default=sa.text("'5.0'"), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_settings_user_id'), 'notification_settings', ['user_id'], unique=1)
    op.create_index(op.f('ix_notification_settings_id'), 'notification_settings', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('ticker', sa.VARCHAR(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('severity', sa.VARCHAR(), server_default=sa.text("'info'"), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('data', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('read_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_ticker'), 'notifications', ['ticker'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    # ### end Alembic commands ###
