"""Add excluded_tickers table

Revision ID: e8d2f847d890
Revises: 171075f06030
Create Date: 2025-11-19 04:20:40.613845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d2f847d890'
down_revision = '171075f06030'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excluded_tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('excluded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_excluded_tickers_id'), 'excluded_tickers', ['id'], unique=False)
    op.create_index(op.f('ix_excluded_tickers_ticker'), 'excluded_tickers', ['ticker'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_excluded_tickers_ticker'), table_name='excluded_tickers')
    op.drop_index(op.f('ix_excluded_tickers_id'), table_name='excluded_tickers')
    op.drop_table('excluded_tickers')
    # ### end Alembic commands ###
